### ISSUE TITLE
Spotifyd configuration outdated.

### ISSUE THREAD

**Issue by juliusdelta** [nathanielevan/dotfiles#1]
Feel free to close if not relevant.

The configuration for `spotifyd` is based on an old version (I think) . `onevent` configuration option appears to have changed to `on_song_change_hook`. Was copying your dunst notification stuff for it and ran across that. I'm on `0.3.0` currently.

Just thought I'd give you a heads up for when you decide to upgrade or anything.

Cheers on the great config.

**Comment by nathanielevan** [comment]
Oh shoot, I didn't realise that `on_song_change_hook` was already written as a comment in the config file! `onevent` still works for me so I didn't notice anything, but in case the option has been deprecated and will be unsupported in the near future, I've changed `onevent` to `on_song_change_hook` to be safe. Thanks!

**Comment by nathanielevan** [comment]
Closing this issue, feel free to re-open it if you need to.
